(provide 'n-modes)

(defun n-modes-lispy-p()
  (or (eq major-mode 'lisp-interaction-mode)
      (eq major-mode 'emacs-lisp-mode)
      (let(
           (bN	(buffer-name))
           )
        (require 'nmidnight)
        (or (equal bN "*Help*")
            (equal bN "*Compile-Log*")
            (equal bN ".emacs")
            (equal bN "n-database")
            (equal bN "ef")
            (equal bN "ev")
            (equal bN "t")
            (equal bN ".vm")
            (equal bN "*scratch*")
            (equal bN "*trace*")
            (equal bN "*Completions*")
            (equal bN "*Backtrace*")
            (and (equal bN midnight-grep-output-buffer)
                 (save-excursion
                   (forward-line 0)
                   (looking-at ".*/lisp/")
                   )
                 )
            )
        )
      )
  )

(defun n-modes(module func)
  (if (not (featurep module))
      (require module))
  (funcall func)
  )

(add-hook 'emacs-lisp-mode-hook 'nelisp-mode)
(add-hook 'comint-output-filter-functions 'shell-strip-ctrl-m nil)
(add-hook 'emacs-lisp-mode-hook 'nelisp-mode)

(defun nez-mode()		(interactive)(n-modes 'nez 	'nez-mode-meat))
(defun nhbm-mode()		(interactive)(n-modes 'nhbm 	'nhbm-mode-meat))
(defun nant-mode()		(interactive)(n-modes 'nant 	'nant-mode-meat))
(defun nfacts-mode()		(interactive)(n-modes 'nfacts 	'nfacts-mode-meat))
(defun nst-mode()		(interactive)(n-modes 'nst 	'nst-mode-meat))
(defun nmenu-edit-mode()	(interactive)(n-modes 'nmenu-edit 	'nmenu-edit-mode-meat))
(defun nhtml-mode()		(interactive)(n-modes 'njava 	'nhtml-mode-meat))
(defun njava-mode()		(interactive)(n-modes 'njava 	'njava-mode-meat))
(defun njavascript-mode()	(interactive)(n-modes 'njava 	'njavascript-mode-meat))
(defun njsp-mode()		(interactive)(n-modes 'njava 	'njsp-mode-meat))
(defun n-gdbinit-mode()		(interactive)(n-modes 'n-gdb	'n-gdbinit-mode-meat))
(defun nbookkeeping-mode()	(interactive)(n-modes 'nbookkeeping	'nbookkeeping-mode-meat))
(defun nclass-browser-mode()	(interactive)(n-modes 'nclass-browser	'nclass-browser-mode-meat))
(defun ndcm-mode()		(interactive)(n-modes 'ndcm	'ndcm-mode-meat))
(defun nelisp-mode()		(interactive)(n-modes 'nelisp	'nelisp-mode-meat))
(defun nfiles-mode()		(interactive)(n-modes 'nfiles	'nfiles-mode-meat))
(defun nmidnight-mode()		(interactive)(n-modes 'nmidnight	'nmidnight-mode-meat))
(defun nmw-data-mode()		(interactive)(n-modes 'nmw-data	'nmw-data-mode-meat))
(defun nperl-mode()		(interactive)(n-modes 'nperl	'nperl-mode-meat))
(defun nplsql-mode()		(interactive)(n-modes 'nplsql	'nplsql-mode-meat))
(defun nps-mode()		(interactive)(n-modes 'nps	'nps-mode-meat))
(defun nrecord-mode()		(interactive)(n-modes 'nrecord	'nrecord-mode-meat))
(defun npix-control-mode()	(interactive)(n-modes 'npix-control	'npix-control-mode-meat))
(defun npython-mode()		(interactive)(n-modes 'npython	'npython-mode-meat))
(defun nahk-mode()		(interactive)(n-modes 'nahk	'nahk-mode-meat))
(defun nsh-mode()		(interactive)(n-modes 'nsh	'nsh-mode-meat))
(defun nps1-mode()		(interactive)(n-modes 'nps1	'nps1-mode-meat))
(defun nshovel-mode()		(interactive)(n-modes 'nshovel	'nshovel-mode-meat))
(defun nshovel-list-mode()	(interactive)(n-modes 'nshovel	'nshovel-list-mode -meat))
(defun nsql-mode()		(interactive)(n-modes 'nsql	'nsql-mode-meat))
(defun nsql-interactive-mode()	(interactive)(n-modes 'nsql	'nsql-interactive-mode-meat))
(defun nsummary-mode()		(interactive)(n-modes 'nsummary	'nsummary-mode-meat))
(defun nmw-mode()		(interactive)(n-modes 'nteacher	'nmw-mode-meat))
(defun nteacher-mode()		(interactive)(n-modes 'nteacher	'nteacher-mode-meat))

(defun nmenu(&rest args) (require 'nmenu) (apply 'nmenu-choose args))
(defun nshell(&rest args) (interactive "P") (require 'nshell) (apply 'nshell-meat args))
(defun ntrc-func(&rest args) (interactive) (require 'ntrc) (apply 'ntrc-func-meat args))
