(provide 'n3)
(defun n-toggle( &optional arg)
  "n3.el: toggle some variable; with optional arg, allow typamatic toggling"
  (interactive "p")
  (message "toggle: ")
  (let(
       (cmd (read-char))
       )
    (cond
     ((= cmd ?d) (ndiff-toggle-echo))
     ((= cmd ?e) (n-host-devo-cycle))
     ((= cmd ?E) (n-host-devo-cycle)
      (while (eq ?E (read-char))
        (n-host-devo-cycle)
        )
      )
     ((= cmd ?f) (n-font-cycle))
     ((= cmd ?F)
      (n-font-cycle)
      (while (eq ?F (read-char))
        (n-font-cycle)
        )
      )
     ((= cmd ?g) (require 'n-grab)	(n-grab-file-toggle-behavior))
     ((= cmd ?l) (require 'n-mv-line)	(n-mv-line-toggle-trait))
     ((= cmd ?m) ( n-genmake-toggle))
     ((= cmd ?O) (n-cycle-env-groups))
     ((= cmd ?r) (toggle-read-only))
     ((= cmd ?w) (setq n-cc-warnings (not n-cc-warnings )))
     (t (error "%c: Not ([Cc]-cycle-env, o-opposing view,r-r/o, g-grab file parm, l-lines-mv parm." cmd))
     )
    )
  )
