(provide 'ncl)
(defun ncl-sccs-edit(fn)
  (find-file (ncl-sccs-fn fn))
  )
(defun ncl-edit(fn)
  (n-host-su-cmd "conadmin")
  (n-host-shell-cmd (format "chmod a+w %s" fn))
  (n-post-for-svr "ncl-edit2" 'ncl-edit2 fn)
  (n-host-shell-cmd (format "%sbin/emacs_client \"M ncl-edit2\"" "~/"))
  )
(defun ncl-edit2(fn)
  (find-file fn)
  (n-file-refresh-from-disk)	; be sure emacs knows I own it
  (nbuf-post-for-kill 'ncl-edit3 fn)
  )
(defun ncl-edit3(fn)
  (n-host-shell-cmd (format "chmod a-w %s" fn))
  (message "%s given back to conadmin" fn)
  (n-host-su-exit)
  )
(defun ncl-cp-to-bugfix(fn)
  (let(
       (distinct	(progn
                          (if (not (string-match "/users/\\([^/]+\\)/[^/]+/\\(.*$\\)"
                                                 fn)
                                   )
                              (error "ncl-cp-to-bugfix: %s" fn))
                          (n--pat 2 fn)
                          )
                        )
       (proj		(n--pat 1 fn))
       bfn
       )
    (setq bfn (concat "/remote/conn7/csi/users/" proj "/bugfix/" distinct ))
    (if (file-exists-p bfn)
        (if (and
             (> (point-max) (point-min))
             (y-or-n-p "overwrite?")
             )
            (copy-file fn bfn t)
          )
      (copy-file fn bfn)
      )
    (find-file bfn)
    )
  )
(defun ncl-mail-bugfix-done(fn)
  (let(
       (user	(progn
                          (if (not (string-match
                                    "/users/oahu/\\([^/]+\\)/"
                                    fn) 
                                   )
                              (error "ncl-mail-bugfix-done: %s" fn))
                          (n--pat 1 fn)
                          )
                )
       )
    (mail nil "cs" (format "%s seems to be broken" n-lprinter) nil)
    )
  )
(defun ncl-sccs-fn(fn)
  (let(
       (sfn	(concat
                 (file-name-directory fn)
                 "SCCS/s."
                 (file-name-nondirectory fn)
                 )
                )
       )
    (if (not (file-exists-p sfn))
        (error "ncl-sccs-fn: "))
    sfn
    )
  )
(defun ncl-backout(fn)
  (n-host-shell-cmd (format "/remote/conn9/csi/users/oahu/nelson/cl/bin/back_out %s" fn))
  )
(defun ncl-obsolete-file(fn)
  (n-host-su-cmd "conadmin")
  (ncl-obsolete-file-conadmin fn)
  (n-host-su-exit)
  )
(defun ncl-obsolete-file-conadmin(fn)
  (let(
       (sfn	(ncl-sccs-fn fn))
       )
    (n-host-shell-cmd (format "cd %s" (file-name-directory fn)))
    (n-host-shell-cmd (format "chmod +w %s . SCCS" fn))
    (n-host-shell-cmd (format "rm  %s" fn))
    (n-host-shell-cmd (format "mv SCCS/s.%s SCCS/S.%s"
                              (file-name-nondirectory fn)
                              (file-name-nondirectory fn)
                              )
                      )
    (n-host-shell-cmd (format "chmod -w . SCCS"))
    )
  )
(defun ncl-refresh-file(fn)
  (save-window-excursion
    (let(
         (sfn	(ncl-sccs-fn fn))
         )
      (n-host-su-cmd "conadmin")
      (n-host-shell-cmd (format "chmod +w %s %s" fn  (file-name-directory fn)))
      (n-host-shell-cmd (format "rm %s" fn))
      (n-host-shell-cmd (format "cd %s" (file-name-directory fn)))
      (n-host-shell-cmd (format "sccs get  %s" (file-name-nondirectory fn)))
      (n-host-shell-cmd (format "chmod -w %s"  (file-name-directory fn)))
      )
    (n-post-for-svr "ncl-refresh-file2" 'ncl-refresh-file2 (buffer-name))
    (n-host-shell-cmd (format "M ncl-refresh-file2"))
    (n-host-su-exit)
    
    (goto-char (point-min))
    (n-s "Sccsid")
    (if (y-or-n-p "refresh locals?")
        (let(
             (ins	(concat fn "\n"))
             (plat	(nfn-plat fn))
             )
          (nsyb-dist-to-local (buffer-file-name))
          (if (not (string= "generic" plat))
              (ncl-refresh-local-disk (concat "/remote/conn5/csi/cron_scripts/new_files." plat) ins)
            (ncl-refresh-local-disk "/remote/conn5/csi/cron_scripts/new_files.axposf" ins)
            (ncl-refresh-local-disk "/remote/conn5/csi/cron_scripts/new_files.hp800" ins)
            (ncl-refresh-local-disk "/remote/conn5/csi/cron_scripts/new_files.sun4" ins)
            (ncl-refresh-local-disk "/remote/conn5/csi/cron_scripts/new_files.sun_svr4" ins)
            (ncl-refresh-local-disk "/remote/conn5/csi/cron_scripts/new_files.ncr" ins)
            (ncl-refresh-local-disk "/remote/conn5/csi/cron_scripts/new_files.rs6000" ins)
            )
          )
      )
    )
  )
(defun ncl-refresh-file2(bn)
  (set-buffer bn)
  (n-file-refresh-from-disk)
  )
(defun ncl-conadmin(fn)
  (n-host-shell-cmd (format "cd %s" (file-name-directory fn)))
  (n-host-su-cmd "conadmin")
  (nshell t)
  )
(defun ncl-refresh-local-disk(fn ins)
  (n-file-push fn)
  (goto-char (point-min))
  (insert ins)
  (save-buffer)
  (n-file-pop)
  )

