(provide 'ncron)
(defun ncron()
  "proc called by cron"
  (ncron-init)
  (load-file (concat (getenv "HOME") "/_nemacs.el"))
  (setq n-batch t)

  (require 'nzip-sniff)
  (n-trace ".emacs check point 10.1")
  (nzip-sniff-all)
  (n-trace ".emacs check point 10.2")

  (nelisp-generate-e_-files)
  (n-trace ".emacs check point 10.3")
  )
(defun ncron-trace(string)
  (save-window-excursion
    (find-file ncron-trace-file)
    (goto-char (point-max))
    (insert string "\n")
    (save-buffer)
    (kill-buffer (current-buffer))
    )
  (message string)
  )
(defun ncron-init()
  (setq ncron-trace-file (concat default-directory "emacs.out"))
  (ncron-trace "ncron-init called...")
  )
