(provide 'ndired)
(defun ndired(dir)
  (dired dir)
  (ndired-clean)
  )
(defun ndired-clean()
  (toggle-read-only)
  (goto-char (point-min))
  (replace-regexp "S-1-5-21-19610888-281770521-1691616715-513" "X              ")
  (goto-char (point-min))
  (replace-regexp "S-1-5-21-1214440339-1645522239-725345543-1004" "X              ")
  (goto-char (point-min))
  (replace-regexp "S-1-5-21-1214440339-1645522239-725345543-513" "X              ")
  (goto-char (point-min))
  (not-modified)
  (toggle-read-only)
  )

(defun ndired-ff()
  "In dired, visit the file or directory named on this line."
  (interactive)
  (let(
       (n-open-file-in-new-window nil)
       )
    (n-file-find (dired-get-filename))
    )
  )
(defun ndired-refresh()
  (interactive)

  (revert-buffer)
  (ndired-clean)
  )

(defun dired-load-hook()
  (define-key dired-mode-map "e" 'ndired-ff)
  (define-key dired-mode-map "" 'dired-do-deletions)
  (define-key dired-mode-map " " 'dired-unflag)
  (define-key dired-mode-map "P" 'n-lpr-dired)
  (define-key dired-mode-map "g" 'ndired-refresh)
  (define-key dired-mode-map "k" 'dired-flag-file-deleted)
  (define-key dired-mode-map "m" 'nsimple-macro-on-file)
  (define-key dired-mode-map "\M-s" 'nshell)
  )
(add-hook 'dired-mode-hook 'dired-load-hook)