(provide 'nteacher_ini)
(defun nteacher_ini-mode-meat()
  (let(
       (map             (make-sparse-keymap))
       )
    (define-key map "\M-c" 'nteacher_ini-do-nmw)
    (define-key map "\M-w" 'nteacher_ini-find-original-answer-text)
    (use-local-map map)
    )
  (setq major-mode 'nteacher_ini-mode
        mode-name "Teacher.ini"
        )
  )
(defun nteacher_ini-do-nmw()
  (interactive)
  (nteacher_ini-find-original-answer-text)
  (nteacher-init-map-words-mode)
  )
(defun nteacher_ini-find-original-answer-text()
  (interactive)
  (let(
       (text (save-excursion
	       (buffer-substring-no-properties (progn
				   (forward-line 0)
				   (n-s "'" t)
				   (n-s "'" t)
				   (n-s "'" t)
				   (point)
				   )
				 (progn
				   (end-of-line)
				   (forward-char -2)
				   (point)
				   )
				 )
	       )
	     )
       (lang (save-excursion
	       (buffer-substring-no-properties (progn
				   (forward-line 0)
				   (n-s "'" t)
				   (point)
				   )
				 (progn
				   (forward-line 0)
				   (n-s "'" t)
				   (n-s "'" t)
				   (forward-char -1)
				   (point)
				   )
				 )
	       )
	     )
       )
    (n-file-find (concat "~/work/adyn.com/httpdocs/teacher/data/" lang "/main.text.html"))
    (goto-char (point-min))
    (n-s (concat "^" text "$") t)
    (forward-line 0)
    )
  )
