(provide 'nterminal)
(defun nterminal-init()
  (setq frame-title-format
        (list
         'multiple-frames "%b"
         (list
          ""
          n-local-user
          "@"
          system-name
          )
         )
        )
  (cond
   (n-is-xemacs
    (set-specifier bottom-toolbar-visible-p nil)
    (set-specifier default-toolbar-visible-p nil)
    (set-specifier left-toolbar-visible-p nil)
    (set-specifier right-toolbar-visible-p nil)
    ;;(set-specifier toolbar-visible-p nil)
    (set-specifier top-toolbar-visible-p nil)

    (set-face-font 'default "arial")
    ;;(set-default-font "8x13bold")
    ;;(setq scroll-bar-mode nil)
    ;;(menu-bar-mode 0)
    (set-frame-size (selected-frame) 152 58)
    )
   ((eq window-system 'x)
    (setq x-pointer-shape x-pointer-circle)
    ;;(setq x-pointer-shape x-pointer-diamond-cross)
    ;;(setq x-pointer-shape x-pointer-based-arrow-down)
    ;;(setq x-pointer-shape x-pointer-based-arrow-up)
    ;;(setq x-pointer-shape x-pointer-boat)
    ;;(setq x-pointer-shape x-pointer-bogosity)
    ;;(setq x-pointer-shape x-pointer-bottom-left-corner)
    ;;(setq x-pointer-shape x-pointer-bottom-right-corner)
    ;;(setq x-pointer-shape x-pointer-bottom-side)
    ;;(setq x-pointer-shape x-pointer-bottom-tee)
    ;;(setq x-pointer-shape x-pointer-box-spiral)
    ;;(setq x-pointer-shape x-pointer-center-ptr)
    ;;(setq x-pointer-shape x-pointer-circle)
    ;;(setq x-pointer-shape x-pointer-clock)
    ;;(setq x-pointer-shape x-pointer-coffee-mug)
    ;;(setq x-pointer-shape x-pointer-cross)
    ;;(setq x-pointer-shape x-pointer-cross-reverse)
    ;;(setq x-pointer-shape x-pointer-crosshair)
    ;;(setq x-pointer-shape x-pointer-dot)
    ;;(setq x-pointer-shape x-pointer-dotbox)
    ;;(setq x-pointer-shape x-pointer-double-arrow)
    ;;(setq x-pointer-shape x-pointer-draft-large)
    ;;(setq x-pointer-shape x-pointer-draft-small)
    ;;(setq x-pointer-shape x-pointer-draped-box)
    ;;(setq x-pointer-shape x-pointer-exchange)
    ;;(setq x-pointer-shape x-pointer-fleur)
    ;;(setq x-pointer-shape x-pointer-gobbler)
    ;;(setq x-pointer-shape x-pointer-gumby)
    ;;(setq x-pointer-shape x-pointer-hand1)
    ;;(setq x-pointer-shape x-pointer-hand2)
    ;;(setq x-pointer-shape x-pointer-heart)
    ;;(setq x-pointer-shape x-pointer-icon)
    ;;(setq x-pointer-shape x-pointer-iron-cross)
    ;;(setq x-pointer-shape x-pointer-left-ptr)
    ;;(setq x-pointer-shape x-pointer-left-side)
    ;;(setq x-pointer-shape x-pointer-left-tee)
    ;;(setq x-pointer-shape x-pointer-leftbutton)
    ;;(setq x-pointer-shape x-pointer-ll-angle)
    ;;(setq x-pointer-shape x-pointer-lr-angle)
    ;;(setq x-pointer-shape x-pointer-man)
    ;;(setq x-pointer-shape x-pointer-middlebutton)
    ;;(setq x-pointer-shape x-pointer-mouse)
    ;;(setq x-pointer-shape x-pointer-pencil)
    ;;(setq x-pointer-shape x-pointer-pirate)
    ;;(setq x-pointer-shape x-pointer-plus)
    ;;(setq x-pointer-shape x-pointer-question-arrow)
    ;;(setq x-pointer-shape x-pointer-right-ptr)
    ;;(setq x-pointer-shape x-pointer-right-side)
    ;;(setq x-pointer-shape x-pointer-right-tee)
    ;;(setq x-pointer-shape x-pointer-rightbutton)
    ;;(setq x-pointer-shape x-pointer-rtl-logo)
    ;;(setq x-pointer-shape x-pointer-sailboat)
    ;;(setq x-pointer-shape x-pointer-sb-down-arrow)
    ;;(setq x-pointer-shape x-pointer-sb-h-double-arrow)
    ;;(setq x-pointer-shape x-pointer-sb-left-arrow)
    ;;(setq x-pointer-shape x-pointer-sb-right-arrow)
    ;;(setq x-pointer-shape x-pointer-sb-up-arrow)
    ;;(setq x-pointer-shape x-pointer-sb-v-double-arrow)
    ;;(setq x-pointer-shape x-pointer-shape)
    ;;(setq x-pointer-shape x-pointer-shuttle)
    ;;(setq x-pointer-shape x-pointer-sizing)
    ;;(setq x-pointer-shape x-pointer-spider)
    ;;(setq x-pointer-shape x-pointer-spraycan)
    ;;(setq x-pointer-shape x-pointer-star)
    ;;(setq x-pointer-shape x-pointer-target)
    ;;(setq x-pointer-shape x-pointer-tcross)
    ;;(setq x-pointer-shape x-pointer-top-left-arrow)
    ;;(setq x-pointer-shape x-pointer-top-left-corner)
    ;;(setq x-pointer-shape x-pointer-top-right-corner)
    ;;(setq x-pointer-shape x-pointer-top-side)
    ;;(setq x-pointer-shape x-pointer-top-tee)
    ;;(setq x-pointer-shape x-pointer-trek)
    ;;(setq x-pointer-shape x-pointer-ul-angle)
    ;;(setq x-pointer-shape x-pointer-umbrella)
    ;;(setq x-pointer-shape x-pointer-ur-angle)
    ;;(setq x-pointer-shape x-pointer-watch)
    ;;(setq x-pointer-shape x-pointer-xterm)

    (set-background-color "black")
    (set-foreground-color "grey")
    ;;(progn (set-background-color "grey") (set-foreground-color "white"))
    ;;(progn (set-background-color "darkgrey") (set-foreground-color "black"))
    ;;(progn (set-background-color "black") (set-foreground-color "lightgreen"))
    (cond
     ((eq system-type 'cygwin)
      (set-cursor-color "red")
      (set-mouse-color "red")
      )
     ((string= n-local-user "nelsons")
      (set-mouse-color "green")
      (set-cursor-color "green")
      )
     ((not (string= n-local-user "nelsons"))
      (set-mouse-color "yellow")
      (set-cursor-color "yellow")
      )
     )
    (set-default-font "8x13bold")
    ;;(set-default-font "10x20")
    (setq scroll-bar-mode nil)
    (menu-bar-mode 0)
    )
   ((and (file-exists-p "c:/")
         (not (string= "19" (substring emacs-version 0 2)))
         )
    (setq default-frame-alist '(
                                (menu-bar-lines . 0)
                                (cursor-color . "red")
                                (cursor-type . box)
                                (foreground-color . "white")
                                (background-color . "black")
                                (font . "-*-Lucida Console-bold-r-*-*-15-112-*-*-c-*-*-ansi-")
                                )
          )
    )
   )
  ;;(set-background-color "black")
  ;;(set-foreground-color "grey")
  (set-face-background 'default "black")
  (set-face-foreground 'default "grey")

  (cond
   ((boundp 'modeline)
    (set-face-foreground 'modeline "black")
    (set-face-background 'modeline "grey")
    )
   (t  ;; v24.3.1
    (set-face-foreground 'mode-line "black")
    (set-face-background 'mode-line "grey")
    )
   )
  ;;(set-face-font 'default "6x13")
  )
(defun nterminal-attention(s)
  (set-foreground-color "black")
  (set-background-color "white")
  (message "%s - hit any key to continue" s)
  (read-char)
  (set-background-color "black")
  (set-foreground-color "white")
  )

(setq nterminal-overlay nil)

(defun nterminal-highlight(on &optional beg end)
  (save-excursion
    (if (or
         (null window-system)
         (eq window-system 'mswindows)
         )
        (nterminal-show-arrow on)

      (if (not on)
          (delete-overlay nterminal-overlay)

        ;; by dft, highlight current line
        (if (not beg)
            (setq beg (progn (forward-line 0)
                             (point)
                             )
                  end (progn (end-of-line)
                             (point)
                             )
                  )
          )
        (or nterminal-overlay (setq nterminal-overlay (make-overlay beg end)))
        (move-overlay nterminal-overlay beg end (current-buffer))
        (overlay-put nterminal-overlay 'face 'region)
        )
      )
    )
  )
(defun nterminal-show-arrow(on)
  (if (not on)
      (setq overlay-arrow-string nil
            overlay-arrow-position nil
            )
    (setq overlay-arrow-string "===>"
          overlay-arrow-position (make-marker)
          )
    (forward-line 0)
    (set-marker overlay-arrow-position (point) (current-buffer))
    )
  )
(defun nterminal-set-one-off-colors()
  (interactive)
  (set-mouse-color "yellow")
  (set-cursor-color "yellow")
    )
  ;;
  ;;
  ;;
  ;; >>>>>>>>>>>>>>>>>>>keep on one line for parsing by em:<<<<<<<<<<<<<<<<<<<<<<<,
  ;;
  ;;
  ;; for gnu 1024 by 768:
  (defun nterminal-1024x768()  (interactive) (set-frame-size (selected-frame) 120 51))

  ;; for gnu 1280 by 1024:
  (defun nterminal-1280x1024() (interactive) (set-frame-size (selected-frame) 151 70))
  
;; for vmware 1280 by 1024:
(defun nterminal-vmware-window-1280x1024() (interactive) (set-frame-size (selected-frame) 152 67))

(if n-is-xemacs
    (set-frame-size (selected-frame) 208 58))
